### PR TITLE
Adding a way to skip minification on a per route basis; Including Xml…

### PR DESCRIPTION
**Pull request by dpenton**
… minification as the Html minifier does not work properly with xml output

### CODE REVIEW

**Comment by ZarehD** [comment]
Thanks David. I like the feature. I'll take a look at the PR as soon as I can.

**Comment by ZarehD** [comment]
Thanks David. This looks great.
There's only a tiny bit of tidying-up I see that I'll do after the merge.
Good catch on the typo, btw (piece vs. peace). Sharp eye ;-)

**Comment by dpenton** [comment]
Glad to do it. Wasn't 100% sure on wording for the documentation that flowed exactly like what you had, so I took a guess. :)

**Comment by ZarehD** [comment]
I'm a bit concerned about the wording for the MinifyOutput property (PageInfo). I don't like that it gives the impression that the output will be minified if this is set to true, which it would only be the case if optimization is requested (not disabled) in the page-generation call. I think I'm going to change this to DontMinify (default False) so that it gives a clearer indication of what this is for. What are your thoughts on that?

**Comment by dpenton** [comment]
I would steer clear of contractions in variable names. That being said, I think the documentation for this property (whatever the name ends up being) should mention the global setting and that if minification is disabled globally then this property is ignored. Now for the name...

https://www.serendipidata.com/posts/naming-guidelines-for-boolean-variables
https://levelup.gitconnected.com/knot-of-nots-avoiding-negative-names-for-boolean-methods-641896a94a42
https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-properties

"Best practices" for property naming tends to suggest "default false". In hindsight I should have considered that more carefully. I think perhaps something along these lines to be more of an affirmative name:

1. PreventMinification
2. PreventMinify
3. PreventMinifiedOutput
4. DisableMinification
5. DisableMinify
6. DisableMinifiedOutput

I think I like `#1` or `#3` best, mainly because `PreventMinification == false` or `!PreventMinification` flows reasonably from a if block perspective, at least when I read it.

**Comment by ZarehD** [comment]
Prevent and Disable might be confusing (could imply global state), but I like Dont and Skip for this. 
I used DontMinify also b/c it's short, but I'd be okay with SkipMinification.

**Comment by dpenton** [comment]
`SkipMinification` works too. I think I was leaning on "prevent" because of `preventEnter` from JavaScript. I'm fine with submitting another PR with `SkipMinification` and documentation updates.

**Comment by ZarehD** [comment]
Okay, `SkipOptimization` it is. No need for a new PR, tho; I've got this.
Thank you, David.

**Pull request merged**
